version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mdb
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "mongodata:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mdb-express
    ports:
      - 8081:8081
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: password
    #  ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

volumes:
  mongodata: